#!/bin/bash
DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

MONSCRIPT=""

LAYOUT_MD5="$(xrandr | grep -oPe ".* connected.*\+" | md5sum | awk '{print $1}')"

case $LAYOUT_MD5 in 
	bef7e2bddb41edd9b85f11ba6e922c90)
		MONSCRIPT="mon-hp-multi"
		;;
	default)
		;;
esac

if [ -n "$MONSCRIPT" ]; then	
	$DIR/$MONSCRIPT
fi
	
	



