#!/bin/bash
 
#Alright, so this should automatically convert a given video into a gif called optimized_output.gif
# See here for explanation: https://github.com/lelandbatey/configDebDev/blob/master/helpFiles.txt#L113
 
TEMP=$(mktemp -d)
ffmpeg -i $1 -q:v 1 -vframes 30 -ss 00:00:03 $TEMP/out_%04d.png # Extracts each frame of the video as a single gif
#rm $TEMP/out_*[13579].png
convert -delay 6 $TEMP/out*.png -dither none $TEMP/anim.gif # Combines all the frames into one very nicely animated gif.
convert -layers Optimize $TEMP/anim.gif $1.gif # Optimizes the gif using imagemagick
 
# vvvvv Cleans up the leftovers
rm $TEMP/out*
rm $TEMP/anim.gif 
