#!/bin/bash
DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

if [ -z $(which i3) ]; then
echo "deb http://debian.sur5r.net/i3/ $(lsb_release -c -s) universe" | sudo tee --append /etc/apt/sources.list 
sudo apt-get update
sudo apt-get --allow-unauthenticated install sur5r-keyring
sudo apt-get update
sudo apt-get install i3 scrot i3lock i3status
fi

mkdir -p ~/.config/i3
cp $DIR/i3config ~/.config/i3/config

#settings set org.gnome.desktop.background show-desktop-icons false

if [ ! -e ~/i3lock-fancy ]; then
pushd ~
git clone https://github.com/meskarune/i3lock-fancy.git
cd i3lock-fancy
git checkout dualmonitors
popd
mkdir -p ~/bin
ln -sfn ~/i3lock-fancy/lock ~/bin/lock
fi

